services:
  # Servidor Central de Automatización (Jenkins)
  jenkins-ci:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins_devsecops_server
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - ./jenkins-data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devsecops-network
    restart: unless-stopped

  # Entorno de Node.js aislado para ejecutar Cypress
  cypress-runner:
    image: cypress/included:13.6.0
    container_name: cypress_qa_runner
    depends_on:
      - jenkins-ci
    volumes:
      - .:/e2e
    networks:
      - devsecops-network
    profiles:
      - tools

networks:
  devsecops-network:
    driver: bridge