version: '3.8'

services:
  # Servidor de automatización Jenkins (Eje central de orquestación de CI/CD)
  jenkins:
    image: jenkins/jenkins:lts-jdk17
    container_name: jenkins-ci
    privileged: true
    user: root
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_data:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devsecops-net
    environment:
      - JAVA_OPTS=-Djenkins.install.runSetupWizard=true

  # Servidor de Seguridad y Calidad de Código Estático (SAST Scan)
  sonarqube:
    image: sonarqube:community
    container_name: sonarqube-sec
    ports:
      - "9000:9000"
    networks:
      - devsecops-net
    volumes:
      - sonarqube_data:/opt/sonarqube/data

networks:
  devsecops-net:
    driver: bridge

volumes:
  jenkins_data:
  sonarqube_data: